export const SCREEN = {
    // Tab
    'SHOP': 'SHOP_SCREEN',
    'CART': 'CART_SCREEN',
    'SEARCH': 'SEARCH_SCREEN',
    'CONTACT': 'CONTACT_SCREEN',
    'TAB': 'TAB',

    // Drawer
    'AUTH': 'AUTH_SCREEN',
    'ORDER_HISTORY': 'ORDER_HISTORY_SCREEN',
    'USER_INFORMATION': 'USER_INFORMATION_SCREEN',
    'DRAWER': 'DRAWER',

    // Main
    'PRODUCT_LIST': 'PRODUCT_LIST_SCREEN',
    'PRODUCT_DETAIL': 'PRODUCT_DETAIL_SCREEN'
}