export const shopTypes = {
  GET_ALL_CATEGORY_AND_PRODUCT: 'GET_ALL_CATEGORY_AND_PRODUCT',
  GET_ALL_CATEGORY_AND_PRODUCT_SUCCESS: 'GET_ALL_CATEGORY_AND_PRODUCT_SUCCESS',
};

export const cartTypes = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  SEND_ORDER: 'SEND_ORDER',
  SEND_ORDER_SUCCESS: 'SEND_ORDER_SUCCESS',
};

export const authTypes = {
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  CHECK_JWT: 'CHECK_JWT',
  CHECK_JWT_SUCCESS: 'CHECK_JWT_SUCCESS',
  CHANGE_USER_INFORMATION: 'CHANGE_USER_INFORMATION',
  CHANGE_USER_INFORMATION_SUCCESS: 'CHANGE_USER_INFORMATION_SUCCESS',
  SIGN_OUT: 'SIGN_OUT',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
};

export const productTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_ADD_PRODUCTS: 'GET_ADD_PRODUCTS',
  GET_ADD_PRODUCTS_SUCCESS: 'GET_ADD_PRODUCTS_SUCCESS',
  GET_SEARCH_PRODUCTS: 'GET_SEARCH_PRODUCTS',
  GET_SEARCH_PRODUCTS_SUCCESS: 'GET_SEARCH_PRODUCTS_SUCCESS',
  GET_CLEAR_PRODUCTS: 'GET_CLEAR_PRODUCTS',
  GET_PRODUCTS_OF_SPRING_COLLECTION: 'GET_PRODUCTS_OF_SPRING_COLLECTION',
  GET_PRODUCTS_OF_SPRING_COLLECTION_SUCCESS:
    'GET_PRODUCTS_OF_SPRING_COLLECTION_SUCCESS',
  GET_ADD_PRODUCTS_OF_SPRING_COLLECTION:
    'GET_ADD_PRODUCTS_OF_SPRING_COLLECTION',
  GET_ADD_PRODUCTS_OF_SPRING_COLLECTION_SUCCESS:
    'GET_ADD_PRODUCTS_OF_SPRING_COLLECTION_SUCCESS',
};

export const orderTypes = {
  GET_ORDER_HISTORY: 'GET_ORDER_HISTORY',
  GET_ORDER_HISTORY_SUCCESS: 'GET_ORDER_HISTORY_SUCCESS',
};
